package fp.types;

public enum Orbit {
	LOWEARTHORBIT, MEDIUMEARTHORBIT, HIGHEARTHORBIT, GEOSTATIONARYTRANSFERORBIT, 
	SUNSYNCHRONOUSORBIT, POLARORBIT, SUNEARTHORBIT, HELIOCENTRICORBIT, MARSORBIT, EARTHMOONL2,
	SUBORBITAL
}
